### PR TITLE
Update emojipedia.js

### PR DESCRIPTION
**Pull request by SkyWolf369**
Added Heart-Eyes

### CODE REVIEW

**Comment by RishabhDevbanshi** [comment]
Your emoji is out of the object emojipedia. Put it inside the square brackets and you're good to go.

**Comment by SkyWolf369** [comment]
OMG sorry

**Comment by SkyWolf369** [comment]
There you go

**Comment by SkyWolf369** [comment]
Sorry I accidently made a new pr not knowing this one still existed

**Comment by RishabhDevbanshi** [comment]
No problem !

**Pull request closed without merging**
