### PR TITLE
add one more emoji

### PR DESCRIPTION
**Pull request by mayurrajurkar**

### CODE REVIEW

**Comment by RishabhDevbanshi** [comment]
Try to be more descriptive with the meanings.

**Comment by mayurrajurkar** [comment]
now it is more descritive

**Comment by mayurrajurkar** [comment]
please add label hacktoberfest-accepted .
so that my PR counted towards hacktoberfest.

**Comment by RishabhDevbanshi** [comment]
> please add label hacktoberfest-accepted .
> so that my PR counted towards hacktoberfest.

Still try to resolve the merge conflicts .

**Pull request closed without merging**
