### PR TITLE
Add Jolly Roger Flags 🏴‍☠️

### PR DESCRIPTION
**Pull request by hnifmaghfur**
Go Go Pirates 🏴‍☠️ ....

### CODE REVIEW

**Comment by RishabhDevbanshi** [comment]
Before seeing your PR, some more emojis were added. Pls check the list once and then add your emoji at the last with proper id number.

**Comment by hnifmaghfur** [comment]
it's already replace, let's see my PR again.

**Review by RishabhDevbanshi — APPROVED** [review]
Will merge soon !

**Comment by hnifmaghfur** [comment]
its ready to ROCK !

**Pull request closed without merging**
