### PR TITLE
Resolved dependency vulnerabilities (non-breaking)

### PR DESCRIPTION
**Pull request by NullDev**
This PR resolves the 5 dependency security warnings in a non-breaking way. 
Also, it's the base for my follow-up PR which adds a search box, see here: 
https://github.com/RishabhDevbanshi/Emojipedia/pull/43

### CODE REVIEW

**Review by RishabhDevbanshi — APPROVED** [review]
Great work! Will merge it by today.

**Comment by NLDev** [comment]
I resolved the merge conflicts :)

**Comment by NLDev** [comment]
Was this resolved in another PR and shall I close this?

**Comment by NullDev** [comment]
@RishabhDevbanshi Do you need any help maintaining this repository?

**Pull request closed without merging**
